### ISSUE TITLE
Weird circle over brazilian flag

### ISSUE THREAD

**Issue by daynt** [coreui/coreui-icons#10]
There is a weird half circle over the brazil flag.

![chrome_Er34KGW9fA](https://user-images.githubusercontent.com/3105208/71490917-de832f00-282d-11ea-8f59-ba014e9e25dc.png)

`<CIcon class=name="'cif-' + entry.country.countryShort.toLowerCase()"/>`

I'm using Vue.JS with coreui-pro vue 3.0 beta-1 and coreui/icons 1.0.0

**Comment by mrholek** [comment]
@daynt will be fixed in next release
