### ISSUE TITLE
Dist contains git merge conflicts

### ISSUE THREAD

**Issue by jameswilson** [coreui/coreui-icons#12]
When I installed coreui-free-bootstrap-admin-template on branch v3-next and ran `npm run build`  the free.min.css file inside the resulting dist/vendors/@coreui/icons/css/ folder contains git merge conflicts:

<img width="415" alt="Screen Shot 2020-02-04 at 5 18 29 AM" src="https://user-images.githubusercontent.com/243532/73736039-25f2ba00-470e-11ea-9a75-fc64637fdf1f.png">

```
@charset "UTF-8";/*!
<<<<<<< HEAD:scss/free.scss
 * CoreUI Icons Free - Open Source Icons
 * @version v0.4.1
=======
 * CoreUI Icons Free Open Source Icons
 * @version v1.0.0-beta.3
>>>>>>> v1-next:scss/free/free-icons.scss
 * @link https://coreui.io/icons
 * Copyright (c) 2019 creativeLabs Łukasz Holeczek
 * Licensed under MIT (https://coreui.io/icons/license)
 */@font-face{font-family:CoreUI-Icons-Free;src:url(../
```

**Comment by jameswilson** [comment]
Problem is here:

https://github.com/coreui/coreui-icons/blob/7b74ca00be8704704117a7385523fe09970d5ad5/scss/free/free-icons.scss#L1-L12

**Comment by mrholek** [comment]
@jameswilson I will fix it today.

**Comment by mrholek** [comment]
@jameswilson solved!
