### ISSUE TITLE
[cil-delete] Cannot find delete icon in free set

### ISSUE THREAD

**Issue by darthf1** [coreui/coreui-icons#15]
According to [this](https://coreui.io/icons/linear/delete/) the delete icon is a free icon. But I cannot find `cil-delete` in the [free directory](https://github.com/coreui/coreui-icons/tree/master/js/free).

(the same goes for `cil-backspace`)

**Comment by dagi3d** [comment]
@darthf1  I had the same issue and reviewing the commit, I found there https://github.com/coreui/coreui-icons/commit/c6a6ade18494e6882e67790288635bad43bbb961#diff-47089b95db5c34e2781d3c349f65c41d that is was renamed to `cil-remove`
/cc @mrholek
