### ISSUE TITLE
How to use coreui icons pro with coreui react admin template?

### ISSUE THREAD

**Issue by Rishwanth29** [coreui/coreui-icons#19]
Hello,

I purchased CoreUI React Admin Template and then CoreUI Icons Pro package. Since then I was never able to get the Pro Icons to work the way it works like the Free Icons (using the element).

Is there a documentation that I can use? Obviously there is a missing here. You should have a support forum, or documentation on how to use the package.

**Comment by xidedix** [comment]
Hello @Rishwanth29 
Please contact us https://coreui.io/support/
