### ISSUE TITLE
can't use icons 

### ISSUE THREAD

**Issue by Fengtao1314520** [coreui/coreui-icons#26]
I  download coreui-free-vue-admin-template and want use whole icon from 'coreui-icons'
my code is:
in main.js
`import { freeSet, brandSet, flagSet } from '@coreui/icons'`
` new Vue({
  el: '#app',
  router,
  store,
  icons: { freeSet, brandSet, flagSet },
  template: '<App/>',
  components: {
    App,
  },
})`
in vue file
`<CIcon name="cil-pregnant" />`
but it not work it,

![image](https://user-images.githubusercontent.com/4384247/91924278-dbb5d380-ed04-11ea-9d79-ab7fcc0cb3dc.png)

**Comment by woothu** [comment]
Those are icon sets, you need to spread them:

```
icons: { ...freeSet, ...brandSet, ...flagSet }
```
