### ISSUE TITLE
CoreUI icons package is huge!

### ISSUE THREAD

**Issue by eddivalen** [coreui/coreui-icons#34]
How can I reduce the bundle size of the icons package?

Currently, the size is 10.2MB

I’m just importing these ones:
```
//icons.js    
import {
      cilEnvelopeClosed,
      cilEnvelopeOpen,
      cilMagnifyingGlass,
      cilMoon,
      cilSpeedometer,
      cilSun,
      cilAccountLogout,
      cilUser,
      cilXCircle,
      cilX,
    } from '@coreui/icons'

import { logo } from './logo'

export const iconsSet = Object.assign({}, { logo }, {
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilMagnifyingGlass,
  cilMoon,
  cilSpeedometer,
  cilSun,
  cilAccountLogout,
  cilUser,
  cilXCircle,
  cilX,
})
```

```
//main.js
import { iconsSet as icons } from './assets/icons/icons.js'
...
...
...
new Vue({
  el: '#app',
  router,
  store,
  icons
  components: {
    App
  },
  template: '<App/>',
  apolloProvider: createProvider(),
})
```
![image](https://user-images.githubusercontent.com/8193094/112513037-53635280-8d6a-11eb-9af2-8801208ab2f9.png)

**Comment by xidedix** [comment]
@eddivalen huh?
Obviously you've got imports of `freeSet`, `brandSet` and `flagSet` somewhere in the code. I suspect `src/views/icons`.

With your example I've got: 
![image](https://user-images.githubusercontent.com/20643598/112653356-9e569600-8e4e-11eb-9104-06c23b9081bb.png)

**Comment by eddivalen** [comment]
Hey @xidedix, thanks for your answer, I just made a build in production mode and I get that 6 KB

Do you know why this only works in production mode?

**Comment by xidedix** [comment]
@eddivalen Webpack `production` mode configuration option enables tree shaking and other optimizations.
