### ISSUE TITLE
Done payment 2 month ago. When should I get the 2000 icons pack?

### ISSUE THREAD

**Issue by cnyyk** [coreui/coreui-icons#4]
Done payment 2 month ago. When should I get the 2000 icons pack?

All 902 Icons (Over 2.000 will be available soon)

Payment is for 2000 icons, not for the 902 icons.

**Comment by mrholek** [comment]
Over 1400 icons will be ready to download at the beginning of next month.

**Comment by cnyyk** [comment]
OK. waiting for that.

**Comment by xidedix** [comment]
I'm closing this since it appears to be inactive or answered above. Feel free to comment or reopen if the issue has not been resolved.
